"""add name field nullable

Revision ID: 046f64a8a714
Revises: 204eac714f6d
Create Date: 2025-11-23 22:22:07.276754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046f64a8a714'
down_revision = '204eac714f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
